name: Build

on:
  push:
    branches: ['main']

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v2

      - name: Build Node Windows
        run: |
          cd deno
          deno compile -A --target x86_64-pc-windows-msvc --output nico-renamer-deno ./main.ts

      - name: Build Node MacOS
        run: |
          cd deno
          deno compile -A --target x86_64-apple-darwin --output nico-renamer-deno ./main.ts

      - name: Setup Zig
        uses: mlugg/setup-zig@v1
        with:
          version: master

      - name: Build Zig Windows
        run: |
          cd zig
          zig build --release=safe -Dtarget=x86_64-windows

      - name: Build Zig MacOS
        run: |
          cd zig
          zig build --release=safe -Dtarget=x86_64-macos

      - name: Get current date
        id: date
        run: |
          echo "builddate=$(date +'%Y-%m-%dT%H-%M-%S')" >> $GITHUB_ENV

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          name: nightly-${{ env.builddate }}
          tag_name: nightly-${{ env.builddate }}
          files: |
            deno/nico-renamer-deno.exe
            deno/nico-renamer-deno
            zig/zig-out/bin/nico-renamer.exe
            zig/zig-out/bin/nico-renamer
